version: '3'

services:

  flask:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    container_name: flask
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGO_DB_ADDR: mongodb
    volumes:
      - ./services/backend:/usr/src/app
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      # db-data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
#    volumes:
#      - ./mongo-mongo-init.js:/docker-entrypoint-initdb.d/mongo-mongo-init.js:ro
    networks:
      - backend


  nginx:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - flask
    networks:
      - frontend

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    volumes:
      - './services/frontend/app:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - BACKEND_SERVICE_URL=http://127.0.0.1:5001
      - VUE_GATEWAY_URL=http://127.0.0.1:3007
    depends_on:
      - flask
    networks:
      - frontend


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
  nginxdata:
    driver: local
